#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing';

# Check Prettier

npm run check-format || 
{ 
    echo 'Prettier Check Failed. Run npm run format, add changes and try again';
    false;
}

# Check ES Lint

npm run check-lint || 
{
    echo 'ESLint Check Failed, Make the required changes listed above, add changes and try to commit again';
    false;
}

# Check TS config

npm run check-types || 
{
    echo 'Failed type check, Make the changes required above, add changes and try to commit again';
    false;
}

npm run build ||
{
    echo 'Your build failed. view the errors above';
    false;
}

echo 'Success commit';